# Generated by Django 4.1.3 on 2022-11-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("email", models.EmailField(max_length=128, verbose_name="이메일")),
                ("name", models.CharField(max_length=32, verbose_name="이름")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="활성화 여부"),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="직원 여부")),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="어드민 계정 여부"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저 목록",
                "db_table": "users",
            },
        ),
    ]
